spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: school_route
            uri: http://localhost:8081
            predicates:
              - Path=/school-service/**
          - id: student_route
            uri: http://localhost:8082
            predicates:
              - Path=/student-service/**


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
